spring:
  mvc:
     pathmatch:
        matching-strategy: ANT_PATH_MATCHER
  application:
     name: EbankMat
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cqjdudb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 0
      acks: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.ebank.jwt.system.kafka.EbankSerializer
    consumer:
      group_id: javagroup
      enable-auto-commit: false
      auto-commit-interval: 100
      auto-offset-reset: latest
      max-poll-records: 50
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.ebank.jwt.system.kafka.EbankDeserializer

mybatis-plus:
  config-location:
    mapper-locations:
      - classpath:mapper/*.xml
      - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

springfox:
  documentation:
    enabled: true
server:
  port: 8880
ebank:
  currency: CNY
  jwt:
    enabled: true
    secret: ebank
    expiration: 3600000
    header: Authorization
    userParamName: username
    pwdParamName: password
    corsAllowedOrigins:
      - http://localhost:8080
      - http://127.0.0.1:8080
    corsAllowedMethods:
      - GET
      - POST
    useDefaultController: true
  api:
    ignoreUrl: #disable jwt token validation for some urls
      - /user/info
      - http://localhost:8888/swagger-ui